name: Update README

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  name: Update this repo's README with latest activity
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - uses: jamesgearge007/github-activity-readme@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
